# Generated by Django 4.2 on 2024-04-25 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="addattendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=50, verbose_name="Day")),
                ("month", models.CharField(max_length=50, verbose_name="month")),
                ("year", models.CharField(max_length=50, verbose_name="year")),
                ("purpose", models.CharField(max_length=50, verbose_name="purpose")),
                (
                    "date_created",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Date Created"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("publication_year", models.IntegerField()),
                ("isbn", models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name="cds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="CDS Name")),
                (
                    "pic",
                    models.CharField(max_length=50, verbose_name="President in Charge"),
                ),
                (
                    "pfcds",
                    models.CharField(max_length=150, verbose_name="Purpose of CDS"),
                ),
            ],
            options={
                "verbose_name": "cdss",
                "verbose_name_plural": "cds",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=50, verbose_name="phone")),
                ("address", models.CharField(max_length=50, verbose_name="address")),
            ],
        ),
        migrations.CreateModel(
            name="CorpRegister",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "firstname",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "lastname",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "statecode",
                    models.CharField(max_length=100, verbose_name="State Code"),
                ),
                (
                    "mystatecode",
                    models.CharField(
                        max_length=50, null=True, verbose_name="corpers Statecode"
                    ),
                ),
                (
                    "sor",
                    models.CharField(max_length=100, verbose_name="State of Origin"),
                ),
                (
                    "statedeployed",
                    models.CharField(max_length=100, verbose_name="State Deployed"),
                ),
                ("cds", models.CharField(max_length=100, verbose_name="CDS")),
                ("batch", models.CharField(max_length=100, verbose_name="Batch")),
                (
                    "pcds",
                    models.CharField(
                        choices=[("Excos", "Excos"), ("Member", "Member")],
                        max_length=100,
                        verbose_name="Post in CDS",
                    ),
                ),
                ("ppa", models.CharField(max_length=100, verbose_name="PPA")),
                (
                    "phone",
                    models.CharField(max_length=100, verbose_name="Phone Number"),
                ),
                (
                    "profile",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="corper_profile/",
                    ),
                ),
                (
                    "status_active",
                    models.CharField(
                        blank=True,
                        choices=[("active", "active"), ("not active", "not active")],
                        max_length=50,
                        null=True,
                        verbose_name="Status Remark",
                    ),
                ),
                (
                    "date_created",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Date Created"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Document Name"),
                ),
                ("purpose", models.CharField(max_length=100, verbose_name="Purpose")),
                (
                    "documenttype",
                    models.ImageField(upload_to="documents", verbose_name="profile"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="user id")),
                (
                    "statecode",
                    models.CharField(
                        max_length=50, null=True, verbose_name="corpers Statecode"
                    ),
                ),
                (
                    "mystatecode",
                    models.CharField(
                        max_length=50, null=True, verbose_name="corpers Statecode"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Year")),
                ("month", models.CharField(max_length=50, verbose_name="Month")),
                ("day", models.IntegerField(verbose_name="Day")),
                ("status", models.IntegerField(verbose_name="Status")),
                (
                    "firstname",
                    models.CharField(max_length=100, verbose_name="Firstname"),
                ),
                ("lastname", models.CharField(max_length=100, verbose_name="Lastname")),
                ("cds", models.CharField(max_length=50, verbose_name="cds")),
                (
                    "profile",
                    models.ImageField(
                        max_length=50,
                        upload_to="corper_profile",
                        verbose_name="profile",
                    ),
                ),
                (
                    "status_active",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Status Remark",
                    ),
                ),
                (
                    "date_created",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Date Created"
                    ),
                ),
            ],
            options={
                "db_table": "Employee",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="goattendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statecode",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="State Code"
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="user id")),
                ("year", models.IntegerField(verbose_name="Year")),
                ("month", models.CharField(max_length=50, verbose_name="Month")),
                ("day", models.IntegerField(verbose_name="Day")),
                (
                    "date_created",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Date Created"
                    ),
                ),
                ("status", models.IntegerField(verbose_name="Status")),
            ],
        ),
    ]
