# Generated by Django 4.2 on 2024-04-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ppa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="PPA Name")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Government", "Government"),
                            ("Private", "Private"),
                            ("Others", "Others"),
                        ],
                        max_length=100,
                        verbose_name="PPA TYPE",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=100, verbose_name="PPA Address"),
                ),
                (
                    "corpNO",
                    models.CharField(max_length=100, verbose_name="PPA Address"),
                ),
                (
                    "empNo",
                    models.CharField(max_length=100, verbose_name="Employer Phone No"),
                ),
            ],
        ),
    ]
