# Generated by Django 4.2 on 2024-04-25 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_ppa"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="user id")),
                (
                    "statecode",
                    models.CharField(
                        max_length=50, null=True, verbose_name="corpers Statecode"
                    ),
                ),
                (
                    "mystatecode",
                    models.CharField(
                        max_length=50, null=True, verbose_name="corpers Statecode"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Year")),
                ("month", models.CharField(max_length=50, verbose_name="Month")),
                ("day", models.IntegerField(verbose_name="Day")),
                ("status", models.IntegerField(verbose_name="Status")),
                (
                    "firstname",
                    models.CharField(max_length=100, verbose_name="Firstname"),
                ),
                ("lastname", models.CharField(max_length=100, verbose_name="Lastname")),
                ("cds", models.CharField(max_length=50, verbose_name="cds")),
                (
                    "profile",
                    models.ImageField(
                        max_length=50,
                        upload_to="corper_profile",
                        verbose_name="profile",
                    ),
                ),
                (
                    "status_active",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Status Remark",
                    ),
                ),
                (
                    "date_created",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Date Created"
                    ),
                ),
            ],
        ),
    ]
