# Generated by Django 4.2 on 2024-04-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_myemployee"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MyEmployee",
            new_name="TakeAttendance",
        ),
    ]
