# Generated by Django 4.2 on 2024-04-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_rename_myemployee_takeattendance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CorpRegister",
        ),
    ]
