# Generated by Django 4.2 on 2024-04-25 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_delete_corpregister"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorpRegister",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "firstname",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "lastname",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "statecode",
                    models.CharField(max_length=100, verbose_name="State Code"),
                ),
                (
                    "mystatecode",
                    models.CharField(
                        max_length=50, null=True, verbose_name="corpers Statecode"
                    ),
                ),
                (
                    "sor",
                    models.CharField(max_length=100, verbose_name="State of Origin"),
                ),
                (
                    "statedeployed",
                    models.CharField(max_length=100, verbose_name="State Deployed"),
                ),
                ("cds", models.CharField(max_length=100, verbose_name="CDS")),
                ("batch", models.CharField(max_length=100, verbose_name="Batch")),
                (
                    "pcds",
                    models.CharField(
                        choices=[("Excos", "Excos"), ("Member", "Member")],
                        max_length=100,
                        verbose_name="Post in CDS",
                    ),
                ),
                ("ppa", models.CharField(max_length=100, verbose_name="PPA")),
                (
                    "phone",
                    models.CharField(max_length=100, verbose_name="Phone Number"),
                ),
                (
                    "profile",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="corper_profile/",
                    ),
                ),
                (
                    "status_active",
                    models.CharField(
                        blank=True,
                        choices=[("active", "active"), ("not active", "not active")],
                        max_length=50,
                        null=True,
                        verbose_name="Status Remark",
                    ),
                ),
                (
                    "date_created",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Date Created"
                    ),
                ),
            ],
        ),
    ]
