# Generated by Django 4.2 on 2024-04-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_corpregister"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CorpRegister",
        ),
    ]
